# -*- coding: utf-8 -*-
"""Summary_Bart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPmaPyLKE6OnvhuS8LRyURrr8yOfYFzQ
"""

import re
import torch
from transformers import BartTokenizer, BartForConditionalGeneration

# Device setup
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Load BART model and tokenizer
print("🔄 Loading BART model...")
model_name = "facebook/bart-large-cnn"
tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name).to(device)

def clean_text(text):
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'\[[^]]*\]', '', text)
    text = re.sub(r'\(.*?\)', '', text)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = text.strip()
    return text

def split_into_chunks(text, max_tokens=1024):
    inputs = tokenizer.encode(text, return_tensors="pt", truncation=False)
    chunks = []
    input_ids = inputs[0]

    for i in range(0, len(input_ids), max_tokens):
        chunk = input_ids[i:i+max_tokens]
        chunks.append(chunk.unsqueeze(0))

    return chunks

def generate_summary(text, max_length=150, min_length=40, do_clean=True):
    if do_clean:
        text = clean_text(text)

    input_ids_chunks = split_into_chunks(text)

    summaries = []
    for input_ids in input_ids_chunks:
        input_ids = input_ids.to(device)
        summary_ids = model.generate(
            input_ids,
            max_length=max_length,
            min_length=min_length,
            num_beams=4,
            length_penalty=2.0,
            early_stopping=True
        )
        summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
        summaries.append(summary)

    return ' '.join(summaries)


if __name__ == "__main__":
    print("\n📜 Paste your long document below. Press Enter twice to summarize:\n")
    lines = []
    while True:
        line = input()
        if not line:
            break
        lines.append(line)

    raw_text = "\n".join(lines)

    print("\n🧠 Generating summary...\n")
    summary = generate_summary(raw_text)
    print("📄 Summary:\n")
    print(summary)